config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :artists, only: [:show, :create]

  resources :favorites, only: [:create, :destroy]

  get "dashboard", to: "pages#dashboard", as: :dashboard
  get "top_10", to: "pages#top", as: :top

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many_attached :photos
  belongs_to :user

  def name
    user.email.match(/^.*@/)[0][0..-2]
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :active_storage_blob, class_name: "ActiveStorage::Blob", foreign_key: "active_storage_blob_id"


  # Just an alias -> it's easier to do .blob instead of .active_storage_blob
  def blob
    active_storage_blob
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites


  def has_favorite?(blob)
    favorites.map(&:blob).include?(blob)
  end

  def favorite_of(blob)
    favorites.find_by(active_storage_blob: blob)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :set_artist, only: [:show, :create]


  def show; end

  def new
    @artist = Artist.new
  end

  def create
    @artist.user = current_user
    if @artist.save
      redirect_to artist_show_path
    else
      render :new
    end
  end

  private

  def artist_params
    params.require(:artist).permit(:bio, :specialty)
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    blob = ActiveStorage::Blob.find(params[:blob])
    favorite = Favorite.new(user: current_user, active_storage_blob: blob)
    favorite.save!
    redirect_to request.referrer
  end

  def destroy
    favorite = Favorite.find(params[:id])
    favorite.destroy
    redirect_to request.referrer
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @photos = Artist.all.map { |artist| artist.photos }.flatten
  end

  def top
    @blobs = Favorite.group(:active_storage_blob_id)
    .select(:active_storage_blob_id)
    .count # Gives an array of hashes, each one containing asb_id and count
    .sort_by { |_k, v| - v } # Sorts by count
    .map { |k, v|  { blob: ActiveStorage::Blob.find(k) , count: v }} # Transforms them into a nicer hash to be used on the view with the full blob instead of just the id and it's count
  end

  def dashboard
    @favorites = current_user.favorites
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/show.html.erb
<div class="container">
  <h1>These are <%= @artist.name %>'s photos:</h1>

  <div class="row">
    <% @artist.photos.each do |photo| %>
      <div class="col-sm-4 my-3">
        <div class="col-12" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.3)), url(<%= cl_image_path photo.blob.key %>); height: 200px; background-position: center; background-size: cover; border: 1px solid black; position: relative;">
        </div>
        <% if current_user.has_favorite?(photo.blob) %>
          <%= link_to favorite_path(current_user.favorite_of(photo.blob)), method: :delete do %>
            <i class="fas fa-heart" style="color: red; position: absolute; top: 4px; right: 24px; font-size: 22px"></i>
          <% end %>
        <% else %>
          <%= link_to favorites_path(blob: photo.blob), method: :post do %>
            <i class="far fa-heart" style="color: red; position: absolute; top: 4px; right: 24px; font-size: 22px"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFavoritePhotos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>These are your favorites:</h1>

  <div class="row">
    <% @favorites.each do |favorite| %>
      <div class="col-sm-4 my-3">
        <div class="col-12" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.3)), url(<%= cl_image_path favorite.blob.key %>); height: 200px; background-position: center; background-size: cover; border: 1px solid black; position: relative;">
        </div>
        <% if current_user.has_favorite?(favorite.blob) %>
          <%= link_to favorite_path(favorite), method: :delete do %>
            <i class="fas fa-heart" style="color: red; position: absolute; top: 4px; right: 24px; font-size: 22px"></i>
          <% end %>
        <% else %>
          <%= link_to favorites_path(blob: favorite.blob), method: :post do %>
            <i class="far fa-heart" style="color: red; position: absolute; top: 4px; right: 4px; font-size: 22px"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1>Browse photos:</h1>
  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-sm-4 my-3">
        <div class="col-12" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.3)), url(<%= cl_image_path photo.key %>); height: 200px; background-position: center; background-size: cover; border: 1px solid black; position: relative;">
        <% if current_user.has_favorite?(photo.blob) %>
          <%= link_to favorite_path(current_user.favorite_of(photo.blob)), method: :delete do %>
            <i class="fas fa-heart" style="color: red; position: absolute; top: 4px; right: 4px; font-size: 22px"></i>
          <% end %>
        <% else %>
          <%= link_to favorites_path(blob: photo.blob), method: :post do %>
            <i class="far fa-heart" style="color: red; position: absolute; top: 4px; right: 4px; font-size: 22px"></i>
          <% end %>
        <% end %>
        </div>
        <p>Photo by: <%= link_to photo.record.name , artist_path(photo.record) %> </p>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/top.html.erb
<div class="container">
  <h1>These are our 10 most favorited photos:</h1>

  <div class="row">
    <% @blobs.each do |blob| %>
      <div class="col-sm-4 my-3">
        <div class="col-12" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.3)), url(<%= cl_image_path blob[:blob].key %>); height: 200px; background-position: center; background-size: cover; border: 1px solid black; position: relative;">
        </div>
        <p><%= blob[:count] %> times favorited </p>
        <% if current_user.has_favorite?(blob[:blob]) %>
          <%= link_to favorite_path(current_user.favorite_of(blob[:blob])), method: :delete do %>
            <i class="fas fa-heart" style="color: red; position: absolute; top: 4px; right: 24px; font-size: 22px"></i>
          <% end %>
        <% else %>
          <%= link_to favorites_path(blob: blob[:blob]), method: :post do %>
            <i class="far fa-heart" style="color: red; position: absolute; top: 4px; right: 24px; font-size: 22px"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Top 10", top_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>